### ISSUE TITLE
Docspace Embed Code not working

### ISSUE THREAD

**Issue by CHOMNANP** [ONLYOFFICE/DocSpace#1602]
https://[xxx].onlyoffice.com/portal-settings/developer-tools/javascript-sdk
I have followed the instruction on the link above.

Then I imported the script into an HTML file.
As a result, the script does not load and only shows "Fallback text".

There is anything else to config to make this work?

**Comment by Misokados** [comment]
Hello @CHOMNANP 
As far as I understand, you have contacted colleagues of mine via Zendesk already. Please do not post the same request on different communication channels, my colleagues are working on your request already.

**Comment by Misokados** [comment]
We are closing this thread since the situation was resolved via Zendesk.
