### ISSUE TITLE
Selfhosted Docker - SMTP settings not applied

### ISSUE THREAD

**Issue by kiroubel-girma** [ONLYOFFICE/DocSpace#1632]
I have a Docker installation (ONLYOFFICE DocSpace v 1.1.1).
I changed the SMTP settings to use an alternate email server.
The test email works correctly.
I verified that the "SMTP test message" is sent via the custom SMTP server I specified.

However every email sent (such as new invite,  welcome message, recovery email, etc.) does not use the custom SMTP server.
Instead all emails come from the default email service (notify.onlyoffice.info)

**Comment by Carazyda** [comment]
Hello @kiroubel-girma Is your problem still persisting? Please try it on the latest version of Docspace.

**Comment by kiroubel-girma** [comment]
I had to switched to package version and it works as intended.
Maybe this is fixed now but I can't test the docker install.
