### ISSUE TITLE
Selfhosted Docker - Custom DNS (Alternate URL) not working.

### ISSUE THREAD

**Issue by kiroubel-girma** [ONLYOFFICE/DocSpace#1633]
I have a Docker installation (ONLYOFFICE DocSpace v 1.1.1).
Things work OK with default local IP address URL ( i.e. http://192.168.0.113).
What I want is to use the fully qualified domain name.
I enabled "DNS Settings", and under "Custom Domain Name" I entered the FQDN (docspace.example.com).
But value is not used at all.  Emails still show the IP address. Invite links also use the IP address URL.

Note that what I really want is to specify an alternate base URL to use (i.e. https://docspace.example.com)
That's because I use a reverse proxy to access the site securely.

**Comment by Irdiism** [comment]
Try with http:// because you do not have an SSL cert when you first configure the domain.

**Comment by Carazyda** [comment]
Hello @kiroubel-girma  Is your problem still persisting? Please try it on the latest version of Docspace.

**Comment by kiroubel-girma** [comment]
I had to switched to package version and it works as intended.
Maybe this is fixed now but I can't test the docker install.
