### ISSUE TITLE
Is there any docker-compose.yml provided to intall?

### ISSUE THREAD

**Issue by xh542428798** [ONLYOFFICE/DocSpace#1813]
Docker-compose.yml is very convenient, like workspace, Is there any docker-compose.yml provided to intall?

**Comment by Irdiism** [comment]
I am not sure if this will be of help, but all docker-compose.yml files are located under /app/onlyoffice/>
They are separated, but I'm sure it's not hard to put them together in one file if you want to do that. 

/app/onlyoffice/build.yml
/app/onlyoffice/dashboards.yml
/app/onlyoffice/db.yml
/app/onlyoffice/dnsmasq.yml
/app/onlyoffice/docspace.overcome.yml
/app/onlyoffice/docspace.profiles.yml
/app/onlyoffice/docspace.yml
/app/onlyoffice/ds.yml
/app/onlyoffice/healthchecks.yml
/app/onlyoffice/migration-runner.yml
/app/onlyoffice/notify.yml
/app/onlyoffice/opensearch.yml
/app/onlyoffice/proxy-ssl.yml
/app/onlyoffice/proxy.yml
/app/onlyoffice/rabbitmq.yml
/app/onlyoffice/redis.yml

**Comment by Carazyda** [comment]
Hello @xh542428798 Yes, all the yml files for each service are located in /app/onlyoffice/ folder if you run installation with our script. Or you can find them in https://github.com/ONLYOFFICE/DocSpace-buildtools/tree/master/install/docker.

**Comment by kerbymart** [comment]
Hi @Carazyda is there a single docker compose file to run DocSpace?

**Comment by Carazyda** [comment]
Hello @kerbymart, sorry, but we don't have a single docker compose file for installing docker right now. All services are split into multiple yml files. We will add this feature in future releases.

For now, we recommend using our script for installation. You can read more in our [help center](https://helpcenter.onlyoffice.com/installation/docspace-community-install-script.aspx).
