### ISSUE TITLE
Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by forqsg** [ONLYOFFICE/DocSpace#1817]
I want to log in to mysql, according to the default user name and password given by the official website, but the login failed, "Access denied for user 'root'@'localhost' (using password: YES)
<img width="427" alt="1715670401083" src="https://github.com/ONLYOFFICE/DocSpace/assets/46246735/12619b0b-3dcb-42fe-a177-5c78a6e0a4b4">

Is there anything wrong with my access to mysql? Where can I get the docker profile for mysql?

**Comment by Irdiism** [comment]
You can find the information you are looking for on the .env file. For me it is under /app/onlyoffice/.env

**Comment by Carazyda** [comment]
Hello @forqsg Yes, you can find this information in `/app/onlyoffice/.env` file. Or by `docker inspect onlyoffice-mysql-server`
