### ISSUE TITLE
Error in login page

### ISSUE THREAD

**Issue by joselmm** [ONLYOFFICE/DocSpace#1821]
Hi, I have been trying to login in my docspace, but there is an error in the login page, when i hit the login button it does not work, nothing happens, here is an image of the error in the devtool (in brave browser the same error):

my docspace domain is: joselmm.onlyoffice.com

![i cannot login in ](https://github.com/user-attachments/assets/0add2b2c-984d-4849-9219-21ccb0b22276)

Here is a preview of the css file that causes the error:

![image](https://github.com/user-attachments/assets/7b8b8df4-484a-481a-b9f9-ae3814ef7618)

also, i'm sure everythings is ok with my account, beacause i am logged in the desktop version and all my files are good

Thank you for your support

**Comment by Misokados** [comment]
Hello @joselmm 
We are checking the situation. I will update this thread as soon as possible.

**Comment by Misokados** [comment]
Hello @joselmm 
Please clear browser cache and cookies one more time and double-check the situation.
