### ISSUE TITLE
Wrong port configuration after docker deployment

### ISSUE THREAD

**Issue by cheng-yeung** [ONLYOFFICE/DocSpace#1822]
Hi, I was deploying docspace community version with docker on my ubuntu 22.04 for a test run last Friday, using the installation sh script you offered. The script ran gracefully, and all docker containers are up (excluding migration container exited). However, so far I have encountered a few issues:
1. After deploying, I was able to access onlyoffice in my browser for the first time and have successfully registered; but the /wizard page have never rendered. Specifically, it loaded for a while, and redirected to /login with an 500 internal server error page rendered.
2. I cannot access any documents. The server logs indicates that `onlyoffice-doceditor` throws an ERR_INVALID_URL, with input 'http://127.0.0.1:8083:8083/api/2.0/files/file/5/openedit?', where 8083 is the external port (-ep) argument I provided to the installation script.
3. I attempt to log in after a while, and even the login page would not render. 
Below is a logged example of failed request:

<img width="645" alt="screenshot" src="https://github.com/user-attachments/assets/40466e65-3af5-495b-bd5a-4e432b49856e">

If needed, the following is the full argument set I ran with (sensitive info replaced with placeholder <>):
```sh
sudo bash docspace-install.sh docker -hub https://dockerhub.icu/ -it community -js <> -mysqlrp <> -mysqlu <> -mysqlp <> -rdsu <> -rdspass <> -rbtu <> -rbtpass <> -dsv latest -docsv latest -mysqlport 33061 -ep 8083
```
All containers are healthy, except for `onlyoffice/docspace-doceditor:latest`. I do believe that these problems are somewhat due to the wrongly configured axios baseUrl "http://:8083:8083". Would you shed some light on this?

**Comment by Carazyda** [comment]
Hello @cheng-yeung Yes, we have an issue with running on a custom external port (-ep). We will fix it in the next release.

**Comment by moritzdawo** [comment]
Hey @Carazyda Can you tell us how long we will have to wait for a fix (or a new release)?

**Comment by Carazyda** [comment]
Fixed in https://github.com/ONLYOFFICE/DocSpace-buildtools/pull/306. New version will be released in about two weeks.
