### ISSUE TITLE
DocSpace restore from backup does not recognise license

### ISSUE THREAD

**Issue by Irdiism** [ONLYOFFICE/DocSpace#1826]
I am not sure if this is a bug, or it is supposed to work like this, but if this is the intended behavior it should be added to the restore docs.

When restoring a backup to DocSpace Spaces (one of multiple Spaces) from third party storage or local storage, once the restore is successful, it pops up a message in the top right corner of the screen that the Trial period ends in 30 days. After re-uploading the license it goes away, but I think it should not have the need to re-upload the license since the license is already located on the server, but it seems that after the restore it just can not read it. 

OS: Ubuntu 22.04
DocSpace version: v2.6.1
Installation type: DEB 

Let me know if i need to provide more information.

**Comment by Carazyda** [comment]
Hello @Irdiism Sorry for the late reply. Yes, you are right, the license should not disappear if we restore one of the space portals. We will fix this in the next version. 

But if you restore all spaces or if you did not configure spaces and will use one main portal - after restoration the license is reset. This is done for security reasons.
