### ISSUE TITLE
How to uninstall DocSpace?

### ISSUE THREAD

**Issue by katorly** [ONLYOFFICE/DocSpace#1827]
I installed DocSpace for Docker on Linux using the provided script. There's no documentation for uninstalling; I only found [this](https://helpcenter.onlyoffice.com/installation/docs-community-remove-docker.aspx), which is not written for DocSpace.

What do I need to do besides deleting all containers, images and volumes from the DocSpace installation script?

Maybe consider adding an `uninstall` option to the installation script?

Containers:  
![image](https://github.com/user-attachments/assets/b2a5e525-89b6-4da5-948e-9b4d60630d81)

Volumes:  
![image](https://github.com/user-attachments/assets/d73f45ba-1dc0-4b26-9641-4fc8b9a72264)

**Comment by Carazyda** [comment]
Hello @katorly we will try to add the `uninstall` option to our script. For now you can remove it manually:
1) Remove containers;
2) Remove images;
3) Remove volumes;
4) Remove the /app/ folder;
5) Remove docker network onlyoffice.

Or remove all docker data with the following command. Be careful if you have another application running in docker - it will remove EVERYTHING! containers\images\volumes of docker.
`docker stop $(docker ps -a -q) && docker system prune -a -f && docker volume rm $(docker volume ls -q) && rm -rf /app/`
