### ISSUE TITLE
install on debian fails without reporting a clear error 

### ISSUE THREAD

**Issue by dsl400** [ONLYOFFICE/DocSpace#1830]
while installing inside docker from .deb I managed to figure out that errors in  `/var/lib/dpkg/info/docspace.postinst`   are sent to `/dev/null` ... after a few hours 

it would be nice to actually know what fails ...

```log
#29 116.9 Setting up docspace (2.6.2.446) ...
#29 117.0 dpkg: error processing package docspace (--configure):
#29 117.0  installed docspace package post-installation script subprocess returned error exit status 1
#29 117.0 Setting up libpython3.11-dev:amd64 (3.11.2-6+deb12u3) ...
#29 117.0 Setting up g++ (4:12.2.0-3) ...
#29 117.0 update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
#29 117.0 Setting up build-essential (12.9) ...
#29 117.0 Setting up libpython3-dev:amd64 (3.11.2-1+b1) ...
#29 117.1 Setting up python3.11-dev (3.11.2-6+deb12u3) ...
#29 117.1 Setting up python3-dev (3.11.2-1+b1) ...
#29 117.1 Processing triggers for libc-bin (2.36-9+deb12u8) ...
#29 117.1 Errors were encountered while processing:
#29 117.1  docspace
#29 117.3 E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Carazyda** [comment]
Hello @dsl400 Can you describe in more detail what command you are running? And what do you want to get as a result?

**Comment by dsl400** [comment]
Hello @Carazyda, I am trying to install  DocSpace on debian bookworm  running in docker 

the command I am running 
```sh
echo docspace docspace/db-pwd select onlyoffice | debconf-set-selections
echo docspace docspace/db-user select onlyoffice | debconf-set-selections
echo docspace docspace/db-name select onlyoffice | debconf-set-selections
DEBIAN_FRONTEND=noninteractive apt -yq install docspace
```
I can see that `docspace.postinst` and `docspace-configuration`  have a lot of  `> /dev/null 2>&1`

so far I managed to find out that inside `docspace-configuration` function `change_mysql_config`  uses  `systemctl` to restart the `mysql` service 


can we have something similar to `DS_DOCKER_INSTALLATION=true apt -yq install onlyoffice-documentserver` for DocSpace ?

**Comment by dsl400** [comment]
That is exactly where I started but because it failed I manually digged down  and got to this conclusion

**Comment by dsl400** [comment]
The average time to install is 15 to 20 minutes if all the stars correctly align. You you are low on luck you sped days reinstalling from scratch because once it passes a specific point the script reports that the product is already installed.

**Comment by Carazyda** [comment]
Sorry, but we don't recommend installing a package version inside a docker container. Try installing the Docspace docker version. Is this not an option for you?

**Comment by dsl400** [comment]
I managed to install it using https://github.com/kvaps/fake-systemd. It all wen smooth after I removed the "WantedBy" from a few services
