### ISSUE TITLE
After setting up one's own SSL certificate, the system cannot access it

### ISSUE THREAD

**Issue by ywzou** [ONLYOFFICE/DocSpace#1831]
After setting up one's own SSL certificate, the system cannot access it
![image](https://github.com/user-attachments/assets/801ae90e-c568-48c8-b056-b9a84dbb21be)

## Response：
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3576187290

**Comment by Carazyda** [comment]
Hello @ywzou Please describe in more detail:
1) How did you install Docspace?
2) What is your server's host OS?
3) How did you apply your own certificates?
4) Is the portal unavailable by IP and domain?

**Comment by ywzou** [comment]
1. Install using official script(`bash docspace-install.sh package`)
2. Rocky Linux 9.4 (Blue Onyx)
3. Using own certificates (`bash /usr/bin/docspace-ssl-setup -f CERTIFICATE PRIVATEKEY`)
4. The ip access is normal

**Comment by ywzou** [comment]
## Error log
TypeError: fetch failed
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (node:internal/deps/undici/undici:7760:28)
      at node:internal/deps/undici/undici:7716:50
      at Immediate._onImmediate (node:internal/deps/undici/undici:7748:13)
      at process.processImmediate (node:internal/timers:476:21)
      at process.callbackTrampoline (node:internal/async_hooks:128:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

**Comment by Carazyda** [comment]
Can you tell me who issued the certificate? Do you have a closed network, no internet access?

**Comment by ywzou** [comment]
Is there a configuration that can directly configure the root path of web `apps/apps/app/documents/api.js`

![image](https://github.com/user-attachments/assets/835e7de4-1826-4ad5-8d1d-53c63c82622e)

**Comment by Carazyda** [comment]
> Is there a configuration that can directly configure the root path of web `apps/apps/app/documents/api.js`
> 
> ![image](https://private-user-images.githubusercontent.com/11622651/387049585-835e7de4-1826-4ad5-8d1d-53c63c82622e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTUwNjIsIm5iZiI6MTczMTkxNDc2MiwicGF0aCI6Ii8xMTYyMjY1MS8zODcwNDk1ODUtODM1ZTdkZTQtMTgyNi00YWQ1LThkMWQtNTNjNjNjODI2MjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA3MjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNjhmYWU2M2RlODFlNjkwM2IyMDA2YmE0YWZhNDIzY2Y2YTFhNGQ1N2IzYzM1YWIwNjYzZmIzMWQ5MGVjY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x4s8vsuUBevM2Ckj9vWn8UaRhxdPOV6OJM-C3QbeqEo)

No, this cannot be configured.

What about this?

> Can you tell me who issued the certificate? Do you have a closed network, no internet access?

**Comment by ywzou** [comment]
1、My actual production request process is` client -->load device -->docspace app server`
2、The` load device` has completed HTTPS data verification, and by the time it reaches the internal `docspace app server`, the certificate has been **uninstalled**. The actual protocol header `X-Forwarded-Protocol` is `HTTP`
